<a href="https://colab.research.google.com/github/sum1t-here/pytorch-fundamentals/blob/main/001pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

print(torch.__version__)

2.11.0+cu128


In [ ]:
## seeing if gpu is available or not

if torch.cuda.is_available():
    print("cuda is available")
    print(torch.cuda.get_device_name(0))
else:
    print("cuda is not available")

cuda is available
Tesla T4


### Creating a tensor

In [ ]:
## using empty

torch.empty(2, 3)

tensor([[1.7666e-29, 0.0000e+00, 5.3274e-16],
        [4.4578e-41, 0.0000e+00, 0.0000e+00]])

In [ ]:
## type

a = torch.empty(2, 3)
type(a)

torch.Tensor

In [ ]:
## using 0's, 1's and rand

a = torch.zeros(2, 3)
print(a)
b = torch.ones(2, 3)
print(b)
c = torch.rand(2, 3)
print(c)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.9900, 0.2948, 0.4040],
        [0.1650, 0.9321, 0.9413]])


In [ ]:
## use of seed

torch.manual_seed(100)
a = torch.rand(2, 3)
print(a)
torch.manual_seed(100)
b = torch.rand(2, 3)
print(b)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [ ]:
## using tensor

torch.tensor([[1, 2, 3],[4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
## other ways

## range 0 to 10 with 2 step
a = torch.arange(0, 10, 2)
print(a)

b = torch.linspace(0, 10, 5)
print(b)

## identity mtx
c = torch.eye(5)
print(c)

d = torch.full((2, 3), 5)
print(d)


tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[5, 5, 5],
        [5, 5, 5]])


In [ ]:
d.shape

torch.Size([2, 3])

In [ ]:
## creating a tensor like another one

torch.empty_like(d)

tensor([[          292631407, 4607182418800017408, 4607182418800017408],
        [4607182418800017408,                  80,                  96]])

In [ ]:
torch.ones_like(d)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.zeros_like(d)

tensor([[0, 0, 0],
        [0, 0, 0]])

### Copying a Tensor

In [ ]:
d = torch.rand(2, 3)
d

tensor([[0.1932, 0.5350, 0.6256],
        [0.5405, 0.3735, 0.4628]])

In [ ]:
a = d
a

tensor([[0.1932, 0.5350, 0.6256],
        [0.5405, 0.3735, 0.4628]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.5350, 0.6256],
        [0.5405, 0.3735, 0.4628]])

In [ ]:
## change in a change d
d

tensor([[0.0000, 0.5350, 0.6256],
        [0.5405, 0.3735, 0.4628]])

In [ ]:
(id(a), id(d))

(139058287705888, 139058287705888)

In [ ]:
## to prevent this use clone

c = a.clone()
c

tensor([[0.0000, 0.5350, 0.6256],
        [0.5405, 0.3735, 0.4628]])

In [ ]:
a[0][1] = 0
a

tensor([[0.0000, 0.0000, 0.6256],
        [0.5405, 0.3735, 0.4628]])

In [ ]:
d

tensor([[0.0000, 0.0000, 0.6256],
        [0.5405, 0.3735, 0.4628]])

In [ ]:
c

tensor([[0.0000, 0.5350, 0.6256],
        [0.5405, 0.3735, 0.4628]])

### Tensor operation on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device("cuda")

In [ ]:
## creating a new tensor on gpu

a = torch.rand((2, 3), device = device)
a

## creating previous tensors on gpu
# a.to(device)

tensor([[0.1671, 0.8815, 0.3172],
        [0.3368, 0.7475, 0.9259]], device='cuda:0')

### Reshape Tensors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
## flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.7329, 0.3730, 0.3730, 0.3644],
         [0.8017, 0.9476, 0.5209, 0.5014],
         [0.5012, 0.2877, 0.1787, 0.6071]],

        [[0.6987, 0.6703, 0.1632, 0.3492],
         [0.1521, 0.5169, 0.7198, 0.6662],
         [0.4614, 0.0194, 0.4069, 0.1911]]])

In [ ]:
b.permute(0, 2, 1)

tensor([[[0.7329, 0.8017, 0.5012],
         [0.3730, 0.9476, 0.2877],
         [0.3730, 0.5209, 0.1787],
         [0.3644, 0.5014, 0.6071]],

        [[0.6987, 0.1521, 0.4614],
         [0.6703, 0.5169, 0.0194],
         [0.1632, 0.7198, 0.4069],
         [0.3492, 0.6662, 0.1911]]])

In [ ]:
## unsqueeze
## image size

c = torch.rand(266, 266, 3)
c.unsqueeze(0).shape

torch.Size([1, 266, 266, 3])

In [ ]:
## squeeze
c = torch.rand(1, 20)
c.squeeze(0).shape

torch.Size([20])

### NUMPY & PYTORCH

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()
b

array([1, 2, 3])

In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
b = torch.from_numpy(a)
b

tensor([1, 2, 3])